### ISSUE TITLE
[Ubuntu] Problem while installing

### ISSUE THREAD

**Issue by jgsogo** [dimi309/conan-ogg#1]
I'm trying your repo https://github.com/coding3d/small3d-conan-example and I came through a couple of _easy to fix_ issues:

## Permissions

![image](https://cloud.githubusercontent.com/assets/1406456/18032611/1232dd88-6d0a-11e6-9e62-16ccd22e9c84.png)

I've entered the `source/_build/ogg` directory inside the `.conan` repos and did:

```
chmod +x configure
```

## Dos line ending

![image](https://cloud.githubusercontent.com/assets/1406456/18032621/62375688-6d0a-11e6-8006-0a5cbe21fc61.png)

Just followed [this instructions](http://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter)

Same problem with the following files:
 * config.sub
 * config.guess
 * missing

## Dependencies :S

```
javi@emo:~/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether gcc and cc understand -c and -o together... yes
checking for ANSI C header files... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking size of int16_t... 2
checking size of uint16_t... 2
checking size of u_int16_t... 2
checking size of int32_t... 4
checking size of uint32_t... 4
checking size of u_int32_t... 4
checking size of int64_t... 8
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking for working memcmp... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating doc/libogg/Makefile
config.status: creating include/Makefile
config.status: creating include/ogg/Makefile
config.status: creating include/ogg/config_types.h
config.status: creating libogg.spec
config.status: creating ogg.pc
config.status: creating ogg-uninstalled.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
javi@emo:~/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2$ make
make  all-recursive
make[1]: Entering directory '/home/javi/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2'
Making all in src
make[2]: Entering directory '/home/javi/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2/src'
Makefile:443: .deps/bitwise.Plo: No such file or directory
Makefile:444: .deps/framing.Plo: No such file or directory
Makefile:445: .deps/test_bitwise-bitwise.Po: No such file or directory
Makefile:446: .deps/test_framing-framing.Po: No such file or directory
make[2]: *** No rule to make target '.deps/test_framing-framing.Po'.  Stop.
make[2]: Leaving directory '/home/javi/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2/src'
Makefile:487: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/javi/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2
javi@emo:~/.conan/data/ogg/1.3.2/coding3d/ci/source/_build/ogg-1.3.2$ 

```
:S

I'll come back here if I manage to pass this stage.

**Comment by jgsogo** [comment]
I haven't got many experience making conan packages, but, is it not possible to checkout svn repository from http://svn.xiph.org/trunk/ogg/, use the `autogen.sh` from there and install the binaries according to conan layout? Following this path I get ogg compiled.

**Comment by coding3d** [comment]
Hi Javier,

The truth is that I don't have a lot of experience either :) I just needed
these packages to compile my own library so I set them up as best as I
could. I think that both your points are correct. It would indeed be good
to be able to pull the trunk version and build it automatically, so I'll
try to set that up. About executing chmod +x on configure, my debian didn't
need it but I saw in other examples that it was being used, so I'll add it,
since it seems to be necessary for some machines. I'll let you know as soon
as I've prepared the new version. Many thanks for the feedback!

**Comment by coding3d** [comment]
By the way I also happily accept pull requests :D

**Comment by coding3d** [comment]
Just a note, I'm still working on this. I don't get a lot of coding time these days but I'll get there...

**Comment by jgsogo** [comment]
Great! Crazy week for me too, I'll try to check it again tomorrow or the
next week... I have a couple of things to do before :/

**Comment by coding3d** [comment]
Hi Javier,

I have managed to make the package build successfully on travis and appveyor. I have added a chmod +x to configure, but I did not encounter the Dos line endings and dependencies issues. I did make one correction with regard to copying the include files though. 

Whenever you try to use the package again, could you please let me know if it works on your system? I plan to also make it download the latest version of the source code but I am taking things step by step. Please note that the package is uploaded to conan.io on the "stable" channel. The "ci" channel contains old builds (and, at the time of writing, I have not changed the references to it from vorbis or small3d).

**Comment by jgsogo** [comment]
I've successfully build your small3d library, so I think this issue can be closed, can't it? ...did you deleted the ```small3d-conan-example``` repo?

**Comment by dimi309** [comment]
Hi Javier,

That's great news!

Indeed, I'm trying to uphold the DRY principle 😂 and I did not want to have two copies of the same source code lying around. You can find the Avoid the Bug sample game, as well as a new one that I am working on in the "samples" directory within the small3d repository. Those are built via conan by default, so they are configured just like the conan example used to be. The new game there is called "Chase the Goat": You are flying the bug instead of driving the goat there😄. The goat is not moving yet, but you can fly around and take a look at the scenery!

Also, notice that we are now on version 1.0.5 and I suggest you use that one, either by linking to it on conan or pulling the master branch from the small3d repository. It is not closed yet, but there are many important improvements. I am using a develop branch for everyday changes and, when things are stable, I merge with the master branch which deploys the version to conan. So the 1.0.5 version on conan (so the conan version is not locked, but stable nonetheless).

Tell me something, since you are using Ubuntu, does sound work there? I've had quite a bit of trouble with it in the past...

Thanks again for all your help by the way! Your portaudio package has saved me a lot of time!

**Comment by dimi309** [comment]
By the way, I've added a changelog.txt to small3d. As you will see there, there are some breaking changes. So better pull the latest version of the sample games from samples directory instead of just upgrading to small3d 1.0.5 in the old conan example. Otherwise, there will be a lot of debugging to do.

**Comment by jgsogo** [comment]
I've already checked out small3d and compile it and the example games, and even sent you a pull request ;D

Everything works ok in my ubuntu.

**Comment by dimi309** [comment]
Wonderful! I'll open the pull request now.
